# This action expects a Docker username and password be stored as environment variables by the calling workflow

name: phil_build_push
inputs:
  registry:
    description: "Registry for image"
    required: false
    default: "philinc"
  name:
    description: "Name of project"
    required: true
  tag:
    description: "Tag to associate with built image"
    required: true
  push:
    description: "Whether or not to push the image to the registry"
    required: false
    default: "false"
runs: 
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
