# This action expects a Docker username and password be stored as environment variables by the calling workflow

name: phil_build_push
inputs: 
  name:
    description: 'Name of project'
    required: true
  tag:
    description: 'Tag to associate with built image'
    required: true
runs: 
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: philinc/${{ inputs.name }}:${{ inputs.tag }}
