name: phil_generate_tag
inputs:
  event:
    description: "Event data"
    required: true
  sha:
    description: "Shortened commit SHA"
    required: true
outputs:
  tag:
    description: "Generated tag based on Git event"
    value: ${{ steps.generate-image-tag.outputs.tag }}
runs:
  using: "composite"
    steps:
      - id: "generate-image-tag"
        env:
          EVENT_CONTEXT: "${{ toJSON(inputs.event) }}"
        shell: bash
        run: |
          EVENT_TYPE=$(echo $EVENT_CONTEXT | jq -r .ref | awk -F/ '{ print $2}')
          REF=$(echo $EVENT_CONTEXT | jq -r .ref | sed -e 's/\// /2' | awk '{print $2}')
          if [ "$EVENT_TYPE" = "tags" ]; then
            echo "::set-output name=tag::$(echo $REF | sed -e 's/v//1')"
            exit 0
          fi
          TAG=${{ inputs.sha }}
          DEFAULT_BRANCH=$(echo $EVENT_CONTEXT | jq -r .repository.default_branch)
          if [ "$REF" != "$DEFAULT_BRANCH" ]; then
            if [[ $REF = feature/* ]]; then
              TAG=$(echo "$REF" | sed -e 's/feature\///g' -e 's/_/-/g' | awk '{print tolower($0)}')-$TAG
            else
              echo "::set-output name=tag::''"
              exit 0
            fi
          fi
          echo "::set-output name=tag::$(echo $TAG)"
          exit 0