---
name: 'Build and Push to ECR and DockerHub'
description: Runs a docker build, then pushes the image to ECR and DockerHub
inputs:
  name:
    description: "Name of project"
    type: string
    required: true
  tag:
    description: "Tag to associate with built image"
    type: string
    required: true
  aws-access-key-id:
    description: "Access key for AWS account"
    type: string
    required: false
    default: ""
  aws-secret-access-key:
    description: "Secret key for AWS account"
    type: string
    required: false
    default: ""
  region:
    description: "Push into this AWS region"
    type: string
    required: false
    default: "us-east-1"
  push:
    description: "Whether or not to push the image to ECR and DockerHub"
    type: boolean
    required: false
    default: false
  dockerfile:
    description: "A path to a Dockerfile to build"
    type: string
    required: false
    default: "Dockerfile"
  notify:
    description: "Whether or not to send a message to gchat"
    type: boolean
    required: false
    default: false
  google-chat-webhook:
    description: "Webhook for sending a google chat notification"
    type: string
    required: false
    default: ""
  docker-username:
    description: "Username for Docker account"
    type: string
    required: false
    default: ""
  docker-password:
    description: "Password for Docker account"
    type: string
    required: false
    default: ""
  docker-registry:
    description: "Docker registry to push images to"
    type: string
    required: false
    default: "philinc"
outputs:
  ecr-registry:
    description: "ECR registry for use with any other tags/pushes"
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - name: Build
    shell: bash
    run: docker build . -t ${{ inputs.docker-registry }}/${{ inputs.name }}:${{ inputs.tag }} -f ${{ inputs.dockerfile }}

  - name: Notify Build
    if: ${{ inputs.notify == 'true' }}
    uses: nakamuraos/google-chat-notifications@v2.0.1
    with:
      title: Build
      subtitle: ${{ github.event.head_commit.message }}
      webhookUrl: ${{ inputs.google-chat-webhook }}
      status: ${{ job.status }}

  - name: Login to DockerHub
    if: ${{ inputs.push == 'true' }}
    shell: bash
    run: docker login -u ${{ inputs.docker-username }} -p ${{ inputs.docker-password }}

  - name: Push to DockerHub
    if: ${{ inputs.push == 'true' }}
    shell: bash
    run: docker push ${{ inputs.docker-registry }}/${{ inputs.name }}:${{ inputs.tag }}

  - name: Configure AWS credentials
    if: ${{ inputs.push == 'true' }}
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.region }}
  
  - name: Login to ECR
    if: ${{ inputs.push == 'true' }}
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2

  - name: Tag for ECR
    if: ${{ inputs.push == 'true' }}
    shell: bash
    run: docker tag ${{ inputs.docker-registry }}/${{ inputs.name }}:${{ inputs.tag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.name }}:${{ inputs.tag }} 

  - name: Push to ECR
    if: ${{ inputs.push == 'true' }}
    shell: bash
    run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}

  - name: Notify Push
    if: ${{ inputs.notify == 'true' && inputs.push == 'true' }}
    uses: nakamuraos/google-chat-notifications@v2.0.1
    with:
      title: Push
      subtitle: ${{ github.event.head_commit.message }}
      webhookUrl: ${{ inputs.google-chat-webhook}}
      status: ${{ job.status }}
