---
name: 'Archive Repo'
description: Package the repository's current state and store it in S3

inputs:

  aws-access-key-id:
    description: "Access key for AWS account"
    type: string
    required: true
    default: ""

  aws-secret-access-key:
    description: "Secret key for AWS account"
    type: string
    required: true
    default: ""

  assume-role:
    description: "The role to assume with permissions to S3"
    type: string
    required: true
    default: ""

  region:
    description: "Push into this AWS region"
    type: string
    required: false
    default: "us-east-1"

  bucket:
    description: "Name of the S3 bucket (and folder path if desired) to store the archive in"
    type: string
    required: false
    default: "phil-code-archives"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Create archive
    shell: bash
    run: |
      mkdir -p archive
      git fetch
      git archive HEAD | gzip > ./archive/repo.tar.gz
      tar -czf ./archive/git.tar.gz .git
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.region }}
      role-to-assume: ${{ inputs.assume-role }}
      role-session-name: CodeArchival
      role-duration-seconds: 1200
  - name: Upload to S3
    shell: bash
    run: |
      aws s3 cp ./archive/repo.tar.gz s3://${{ inputs.bucket }}/${{ github.repository }}/${{ github.ref_name }}/repo.tar.gz
      aws s3 cp ./archive/git.tar.gz s3://${{ inputs.bucket }}/${{ github.repository }}/${{ github.ref_name }}/git.tar.gz
