# Expects docker_username and docker_password secrets to be inherited

name: phil_build_push
on:
  workflow_call:
    inputs:
      registry:
        description: "Registry for image"
        type: string
        required: false
        default: "philinc"
      name:
        description: "Name of project"
        type: string
        required: true
      tag:
        description: "Tag to associate with built image"
        type: string
        required: true
      push:
        description: "Whether or not to push the image to the registry"
        type: boolean
        required: false
        default: false
jobs:
  build_and_push:
    runs-on: self-hosted
    container: 
      image: "docker:latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ inputs.push }}
          tags: ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
