# Expects docker_username and docker_password secrets to be inherited

name: phil_build_push
on:
  workflow_call:
    inputs:
      registry:
        description: "Registry for image"
        type: string
        required: false
        default: "philinc"
      name:
        description: "Name of project"
        type: string
        required: true
      tag:
        description: "Tag to associate with built image"
        type: string
        required: true
      push:
        description: "Whether or not to push the image to the registry"
        type: boolean
        required: false
        default: false
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: docker build . -t ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
      - name: Login to DockerHub
        if: ${{ inputs.push }}
        run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Push
        if: ${{ inputs.push }}
        run: docker push ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}

