name: phil_helm_package
on:
  workflow_call:
    inputs:
      directories:
        description: 'Stringified JSON object listing directories to build'
        default: ''
        required: false
        type: string
jobs:
  helm_package:
    container: 
      image: dtzar/helm-kubectl:3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{fromJson(inputs.directories)}}
    steps:
    - name: Package chart
      run: helm package . --dependency-update
