name: Archive repo on master or tag push
on: 
  push:
    branches:
    - master
    tags:
    - 'v*'
jobs:
  archive:
    name: Archive Repository
    runs-on: ubuntu-latest
    steps:
    - name: archive-repo
      uses: phil-inc/public-actions/.github/actions/archive-repo@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        assume-role: ${{ secrets.ARCHIVE_CODE_REPOSITORIES_ROLE }}